apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  namespace: payments

spec:
  securityContext:
    runAsNonRoot: true

  containers:
    - name: nginx
      image: nginx:latest

      securityContext:
        allowPrivilegeEscalation: false

        capabilities:
          drop:
            - ALL